# Application Configuration
spring.application.name=Hotel Room Management
server.port=8080


# PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/hotel_db
spring.datasource.username=hotel_user
spring.datasource.password=hotel_pass
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Static Resources
spring.web.resources.static-locations=classpath:/static/

# Logging
logging.level.com.hotelroom=DEBUG
